plugins {
    // this is necessary to avoid the plugins to be loaded multiple times
    // in each subproject's classloader
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.androidLibrary) apply false
    alias(libs.plugins.composeMultiplatform) apply false
    alias(libs.plugins.composeCompiler) apply false
    alias(libs.plugins.kotlinMultiplatform) apply false
    alias(libs.plugins.kotlinSerialization) apply false
    alias(libs.plugins.ksp) apply false
    alias(libs.plugins.spotless)
    alias(libs.plugins.detekt)
    // Version-catalog linter/formatter (sorts libs.versions.toml, flags unused entries).
    // Applied to the root project only. Auto-update is intentionally left unused so it
    // does not compete with Dependabot; use the `versionCatalogFormat` task for linting.
    alias(libs.plugins.versionCatalogUpdate)
}

allprojects {
    apply(plugin = "com.diffplug.spotless")
    apply(plugin = "io.gitlab.arturbosch.detekt")

    spotless {
        kotlin {
            target("**/*.kt")
            targetExclude(
                "**/build/**/*.kt",
                "**/.idea/**/*.kt",
                "**/bin/**/*.kt",
                "**/generated/**/*.kt",
            )
            // Style base is driven by .editorconfig (ktlint_code_style = android_studio).
            // Spotless only reads per-rule ktlint toggles from here (not from .editorconfig),
            // so the project-level overrides live in this map:
            //  - function-naming: owned by detekt (which exempts @Composable); don't duplicate.
            //  - trailing commas: the Android style guide is silent, so honor Kotlin's official
            //    convention (which encourages them) over the android_studio default of removing.
            ktlint().editorConfigOverride(
                mapOf(
                    "ktlint_standard_function-naming" to "disabled",
                    // IntelliJ-native keys: ktlint honors them and they avoid the
                    // ktlint_* toggle-parsing bug on the trailing-comma properties.
                    "ij_kotlin_allow_trailing_comma" to "true",
                    "ij_kotlin_allow_trailing_comma_on_call_site" to "true",
                ),
            )
        }
        kotlinGradle {
            target("**/*.gradle.kts")
            targetExclude("**/build/**/*.gradle.kts")
            ktlint()
        }
        // Everything non-Kotlin is formatted by Prettier — the de-facto standard for these
        // formats, so this is the "community defaults for non-Kotlin" half of Fit to Standard.
        val prettierExcludes = arrayOf(
            "**/build/**",
            "**/.gradle/**",
            "**/.kotlin/**",
            "**/.idea/**",
            "**/kotlin-js-store/**",
            "**/node_modules/**",
        )
        format("web") {
            target("**/*.html", "**/*.css", "**/*.js")
            targetExclude(*prettierExcludes)
            prettier()
        }
        format("markdown") {
            target("**/*.md")
            targetExclude(*prettierExcludes)
            prettier()
        }
        format("json") {
            target("**/*.json")
            // aboutlibraries.json under composeResources is generated by the aboutLibraries
            // export task; formatting it would fight that task, so skip bundled resources.
            targetExclude(*prettierExcludes, "**/composeResources/**", "**/.claude/**")
            prettier()
        }
        format("yaml") {
            // Prettier only reshapes layout; actionlint validates workflow semantics.
            // They operate on different layers, so the two do not conflict.
            target("**/*.yml", "**/*.yaml")
            targetExclude(*prettierExcludes)
            prettier()
        }
    }

    detekt {
        buildUponDefaultConfig = true
        source.setFrom(files("src"))
        config.setFrom(files("$rootDir/config/detekt/detekt.yml"))
    }
}

// Use the catalog plugin as a pure formatter (sort + normalize), not a pruner.
// versionCatalogFormat would otherwise delete version-only entries such as the
// android-* SDK levels: they are referenced from build scripts via libs.versions.*
// accessors, which the plugin's usage analysis cannot see. keepUnusedVersions guards them.
// (Library/plugin entries are detected via dependency resolution, so they are safe.)
versionCatalogUpdate {
    keep {
        keepUnusedVersions.set(true)
    }
}
