name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    name: Run CI Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'jetbrains'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Check Formatting (Spotless)
        run: ./gradlew spotlessCheck

      - name: Run Linter (Android Lint)
        run: ./gradlew lint

      - name: Run Tests
        run: ./gradlew allTests
